### ISSUE TITLE
Infinite loading when the promotion is not a number

### ISSUE THREAD

**Issue by Pokegali** [aeecleclair/Titan#196]
When creating an account, it is possible to enter something like `E22` into the "Promo" field.
But after that, when the user clicks on the last button to register, it shows a loading animation, and in fact the request has failed.
It would be useful to prevent the user from entering anything else other than numbers in that field.

**Comment by maximeroucher** [comment]
This is due to the fact that integer can be written as scientific form ie 1E22 or even E22

**Comment by Petitoto** [comment]
> On which version of Titan have you find this ?

At least september update. We added the example just after the field to "mitigate this issue".
Bug is still present in latest main.

**Comment by Petitoto** [comment]
Related to #153
