### ISSUE TITLE
Loan editing issue

### ISSUE THREAD

**Issue by Petitoto** [aeecleclair/Titan#197]
When editing a loan, selected items under the search bar don't match the effective selected items in the loan.

![image](https://github.com/aeecleclair/Titan/assets/27863028/adeb557d-aad7-4b0d-8e64-60776f52dc0c)
![image](https://github.com/aeecleclair/Titan/assets/27863028/7f459307-5c43-44e7-8a78-a1dcb8d444fe)

**Comment by maximeroucher** [comment]
I do not succeed to reproduce this bug on preprod

**Comment by julien4215** [comment]
Still able to reproduce the issue
