### ISSUE TITLE
Cinema module issues

### ISSUE THREAD

**Issue by Petitoto** [aeecleclair/Titan#232]
Several issues where introduced since September update

- [x] #64 introduced a bug in cinema module: token is not sent anymore correctly.

For example, see https://github.com/aeecleclair/Titan/commit/1a9f6b28bbf15f5c696688281b9fa1a26c9af8b0#diff-7efa5a22e17b1568eb44010b8074e047a1ef157e7c6237c284f23093de3b1a52L11

- [ ] We should also fix the error message in the logs, which is truncated and not explicit.

![image](https://github.com/aeecleclair/Titan/assets/27863028/925b5aab-cce3-4443-85f7-5b91c5a9df15)

- [x] Unknown issue which prevents to retrieve several fields : "genre", "durée", "poster"
Introduced before november update

- [x] We can't edit poster manually by directly setting the URL (thus, we can't create a session without IMDB)

- [ ] We can't manually set multiline summary

**Comment by maximeroucher** [comment]
I do not have any issue with the token, as depicted in the solving PR.
I can not reproduce your "We can't manually set multiline summary" issue as well.
