### ISSUE TITLE
Password strength

### ISSUE THREAD

**Issue by julien4215** [aeecleclair/Titan#375]
It is not possible to connect to an account that a weak password however it is possible to create it.

**Comment by Marc-Andrieu** [comment]
Same issue. It's possible to log in once (right after you created the account) but not later.
Yet the account still exists in the db (using SQLite).

**Comment by julien4215** [comment]
The root cause is the issue is not the password strength but is described in this issue #379

**Comment by julien4215** [comment]
The root cause is the issue is not the password strength but is described in this issue #379
